src/Entity/Reclamation.php
<?php

namespace App\Entity;
use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "The label is required")]
    #[Assert\Length(
        max: 30,
        maxMessage: "The label cannot exceed {{ limit }} characters"
    )]
    #[Assert\Regex(
        pattern: '/^[A-Z][a-zA-Z\s]/',
        message: "The label must start with a capital letter ."
    )]
    
    private ?string $libelle = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    
    private ?\DateTimeInterface $date_decl = null;
    public function __construct()
    {
        $this->date_decl = new \DateTime();
        $this->date_sin = new \DateTime();
    }
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: false)]
#[Assert\LessThanOrEqual("today", message:"The date cannot be in the future.")]
#[Assert\NotBlank(message: "La date ne peut pas être vide.")]

    private ?\DateTimeInterface $date_sin ;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "The content is required")]
    #[Assert\Length(
        min: 10,
        minMessage: "The content of the claim must exceed {{ limit }} characters."
    )]
    private ?string $contenu_rec = null;


   


    #[ORM\Column(nullable: true)]
    private ?string $reponse= "Currently being processed";

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
   
    private ?Indemnissation $indemnissation = null;
     #[ORM\Column(type:"string", length:255, nullable:true)]
   
   private $fileName;




   #[Assert\NotBlank(message: "The latitude is required")]
     #[ORM\Column(length: 50)]
     private ?string $latitude = null;




     
     #[Assert\NotBlank(message: "The longitude is required")]
     #[ORM\Column(length: 50)]



     private ?string $longitude = null;

     #[ORM\ManyToOne(inversedBy: 'reclamations')]
     #[ORM\JoinColumn(nullable: false)]
     //#[ORM\JoinColumn(nullable: false,onDelete:'CASCADE')]
     private ?Commande $command = null;

     

   public function getFileName(): ?string
   {
       return $this->fileName;
   }

   public function setFileName(?string $fileName): self
   {
       $this->fileName = $fileName;

       return $this;
   }
    
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }
    public function getDateDecl(): ?\DateTimeInterface
    {
        return $this->date_decl;
    }

    public function setDateDecl(\DateTimeInterface $date_decl): static
    {
        $this->date_decl= $date_decl;

        return $this;
    }

    public function getDateSin(): ?\DateTimeInterface
    {
        return $this->date_sin;
    }

    public function setDateSin(\DateTimeInterface $date_sin): static
    {
        $this->date_sin = $date_sin;

        return $this;
    }

    public function getContenuRec(): ?string
    {
        return $this->contenu_rec;
    }

    public function setContenuRec(string $contenu_rec): static
    {
        $this->contenu_rec = $contenu_rec;

        return $this;
    }
    
    public function isReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): static
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getIndemnissation(): ?Indemnissation
    {
        return $this->indemnissation;
    }

    public function setIndemnissation(?Indemnissation $indemnissation): static
    {
        $this->indemnissation = $indemnissation;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getCommand(): ?Commande
    {
        return $this->command;
    }

    public function setCommand(?Commande $command): static
    {
        $this->command = $command;

        return $this;
    }

    
 

   
  
  
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'First name cannot be blank')]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Last name cannot be blank')]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Email cannot be blank')]
    #[Assert\Email(message: 'Invalid email format')]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Password cannot be blank')]
    #[Assert\Length(min: 8, minMessage: 'Password must be at least 8 characters long')]
    #[Assert\Regex(
        pattern: '/^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&]).{8,}$/',
        message: 'Password must contain at least one uppercase letter, one digit, and one special character'
    )]
    private ?string $password = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Phone number cannot be blank")]
    private ?int $phone_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message:"Please enter your birth date.")]
    #[Assert\LessThanOrEqual("today", message:"Birth date must not be in the future.")]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\Column(type: 'json')]
    #[Assert\NotBlank(message:"No roles selected.")]
    private ?array $roles = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: 'boolean')]
    private $isBlocked = false;
    
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $secret = null;

    #[ORM\Column(type: 'string', length: 255)]
    private $googleId;

    #[ORM\Column(type: 'text', nullable: true)]
    private $avatar;

    #[ORM\Column(type: 'string', length: 255)]
    private $hostedDomain;

    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'Avis')]
    private Collection $client;
    #[ORM\OneToMany(targetEntity: Commande::class, mappedBy: 'user')]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->client = new ArrayCollection();
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): void
    {
        $this->googleId = $googleId;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): void
    {
        $this->avatar = $avatar;
    }

    public function getHostedDomain(): ?string
    {
        return $this->hostedDomain;
    }

    public function setHostedDomain(?string $hostedDomain): void
    {
        $this->hostedDomain = $hostedDomain;
    }
    
    public function getSecret(): ?string
    {
        return $this->secret;
    }

    public function setSecret(?string $secret): static
    {
        $this->secret = $secret;

        return $this;
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?int $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles(?array $roles): static
{
    $this->roles = $roles;
    return $this;
}

    public function getSalt(){return null;}

    public function eraseCredentials(){}
    public function getUsername(): string{return $this->first_name." ".$this->last_name;}

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    public function isBlocked(): bool
    {
        return $this->isBlocked;
    }

    public function setIsBlocked(bool $isBlocked): static
    {
        $this->isBlocked = $isBlocked;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getClient(): Collection
    {
        return $this->client;
    }

    public function addClient(Avis $client): static
    {
        if (!$this->client->contains($client)) {
            $this->client->add($client);
            $client->setAvis($this);
        }

        return $this;
    }

    public function removeClient(Avis $client): static
    {
        if ($this->client->removeElement($client)) {
            // set the owning side to null (unless already changed)
            if ($client->getAvis() === $this) {
                $client->setAvis(null);
            }
        }

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;


use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Entity\Reclamation;
use App\Entity\File;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $reclamation=$options['data'];
        $builder
        ->add('libelle')
         

      
        ->add('date_sin', DateTimeType::class, [
            'widget' => 'single_text',
            'html5' => true,
            
            
        ])
        ->add('contenuRec', TextareaType::class, [
            'label' => 'Contenu',
            'attr' => [
                'class' => 'form-control',
                'rows' => 5, 
                'style' => 'overflow: hidden;',
            ],
        ])
            ->add('file', FileType::class, [
                'label' => 'Fichier à importer',
                'required' => false, 
                'mapped' => false, 
            ])
            ->add('latitude')
            ->add('longitude')
;
    }
}

templates/reclamation/afficherClaim.html.twig
{% extends 'front_base.html.twig' %}
{% block header %}
    <div id="header-sticky" class="tp-header-area header-transparent header-space header-border" style="background-color: #051B46;">
        <div class="container-fluid">
            <div class="row g-0 align-items-center">
                <div class="col-xxl-2 col-xl-2 col-lg-2 col-md-6 col-6">
                    <div class="tp-logo">
                        <a href="{{ path('app_home') }}"><img src="{{ asset('../front_assets/img/logo/logo.png')}}" alt="hello"></a>
                    </div>
                </div>
                
                <div class="col-xxl-5 col-xl-6 col-lg-5 d-none d-lg-block" style="padding-block-start: 1%; padding-inline-start: 2%;">
                    <div class="tp-main-menu">
                        <nav id="mobile-menu">
                            <ul>
                              
                                <li ><a href="{{ path('display_assuranceF') }}">Insurances</a>
                                <li class="hasdropdown"><a href="#">Policies</a>
                                    <ul class="submenu">
                                        <li><a href="{{ path('front_sinistres') }}">Type of Claim</a></li>
                                        <li><a href="{{ path('front_polices') }}">Policy Details</a></li>
                                    </ul>
                                </li>
                                <li class="hasdropdown"><a href="{{path('app_afficheragencesc')}}">Agencies</a>
                                    <ul class="submenu">
                                    {% if app.user and 'ROLE_ADMIN' in app.user.roles %}
                                        <li><a href="{{path('app_afficheravis')}}">Reviews</a></li>
                                    {% else %}
                                        <li><a href="{{path('app_afficheravisc')}}">review</a></li>
                                    {% endif %}
                                    </ul>
                                </li>
                                    <li><a href="{{path('displayCategorieOffref')}}">Offers</a> </li>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                
                <div class="col-xxl-4 col-xl-3 col-lg-2 col-md-6 col-6" style="padding-block-start: 1%;">
                    <div class="tp-header-right d-flex align-items-center justify-content-end">
                        <div class="tp-header-info d-none d-xxl-block">
                            
                            <div class="tpoffcanvas__social" style="text-align: right;">
                                <div class="social-icon">
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="#"><i class="fab fa-instagram"></i></a>
                                    <a href="https://www.facebook.com/profile.php?id=61556203525394"><i class="fab fa-facebook-square"></i></a>
                                    <a href="#"><i class="fab fa-dribbble"></i></a>
                                </div>
                            </div>
                        </div>
                        {% if app.user %}
                        <div class="tp-main-menu">
                            <nav id="mobile-menu">
                                <ul>
                                    <li class="hasdropdown"><a href="{{path('app_home_manage', {'id': app.user.id})}}">{{ app.user.username }}</a>
                                    <ul class="submenu">
                                            <li><a href="{{path('app_home_manage', {'id': app.user.id})}}">Manage account</a></li>
                                            <li><a href="{{ path('app_logout') }}">Logout</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        {% else %}
                        <div class="tp-header-button d-none d-md-block">
                            <a class="tp-btn" href="{{ path('app_register') }}">SignUp</a>
                        </div>
                        <div class="tp-header-button d-none d-md-block">
                            <a class="tp-btn" href="{{ path('app_login') }}">LogIn</a>
                        </div>
                         {% endif %}
                        <div class="tp-toggle-bar d-lg-none">
                            <a class="tp-menu-bar" href="javascript:void(0)"><i class="fas fa-bars"></i></a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

   <!-- tp-header-area-end -->
   </header>
{% endblock %}
{% block main %}
<main>
{% block slider %}

      
        <br><br>
<style>
 .btn {
        background-color: #f8f9fa;
        color: #007bff;
    }
    .btn:hover {
    background-color: #fcaf3d; /* Couleur de fond jaune */
    color: #f8f9fa; /* Couleur du texte noire */
}
.small-image {
    max-width: 100px;
    max-height: 100px;
    transition: all 0.3s ease; /* Animation de transition pour un agrandissement en douceur */
}

.expanded-image {
    max-width: none; /* Supprimez la limitation de la largeur */
    max-height: none; /* Supprimez la limitation de la hauteur */
    cursor: zoom-out; /* Changez le curseur pour indiquer qu'il est possible de cliquer à nouveau pour réduire l'image */
}
    .espacement-superieur {
        padding-top: 100px; /* Ajustez selon vos besoins pour espacer du haut */
    }
    .contenu-centre {
        display: flex;
        flex-direction: column;
        justify-content: center; /* Centrage vertical */
        min-height: 100vh; /* Hauteur de vue minimale pour prendre toute la hauteur de l'écran */
    }
    .couleur-carte {
        background-color: #f0f0f0; /* Couleur de fond des cartes, ajustez à votre préférence */
    }
</style>

<div class="contenu-centre">
    <div class="container espacement-superieur">
        {% block service %}
<style>
    .custom-margin-top {
        margin-top: 7rem; 
    }
</style>

     <div class="tp-service-shape-1">
                    <img src="front_assets/img/slider/02_Shape.png" alt="">
                </div>
                <div class="tp-service-shape-2">
                    <img src="front_assets/img/slider/03_Shape.png" alt="">
                </div>
                <div class="container">
                <div class="table-responsive">
                    

<table class="table">
        <tbody>
          
         <tr>
        <th style="color: purple;">map</th>
          <td style="width:900px; height: 250px;">
    <iframe src='https://www.google.com/maps?q={{ rec.latitude }},{{ rec.longitude }}&h1=es;z=14&output=embed' style="width: 100%; height: 100%; border: 0;"></iframe>
</td>
 </tr>
         <tr>
        <th style="color: purple;">image</th>
          <td>
        {% if rec.getFileName() is not null %}  <img src="{{ asset('uploads/' ~ rec.fileName) }}" alt="{{ rec.fileName }}"
class="small-image" onclick="expandImage(this)">
    {% else %} ------{% endif %}</p>

    </td>
        </tr>
            <tr>
                <th style="color: purple;">Id</th>
                <td style="color: black;">{{ rec.id }}</td>
            </tr>
            <tr>
                 <th style="color: purple;">Label</th>
                <td style="color: black;">{{ rec.libelle }}</td>
            </tr>
            <tr>
    <th style="color: purple;">Date Claim</th>
    <td style="color: black;">{{ rec.dateDecl ? rec.dateDecl|date('Y-m-d H:i:s') : ''}}</td>
</tr>
<tr>
    <th style="color: purple;">Date Sinistre</th>
    <td style="color: black;">{{rec.dateSin ? rec.dateSin|date('Y-m-d H:i:s') : ''  }}</td>
</tr>

           <tr>
    <th style="color: purple;">Content</th>
    <td style="color: black;">
        <p>{{ rec.contenuRec }}</p>
    </td>
</tr>
                 <th style="color: purple;">Reponse</th>
                <td style="color: black;">{{ rec.reponse }}</td>
            </tr>
            
        </tbody>
    </table>
    {% if rec.isReponse() == 'refused' or rec.isReponse() == 'accepted' %}
     {% if rec.getIndemnissation() is not null %}
        <a href="{{ path('indemnisationUser_show',{'id': rec.getIndemnissation().getId()}) }}"> {% endif %}
            <button type="button" class="btn btn-light btn-round px-2"><i class="icon-lock"></i>Show Compensation</button>
        </a>{% else %}
       <a href="{{ path('recc_editUser', {'id': rec.id}) }}"> <button type="button" class="btn btn-light btn-round px-2"><i class="fas fa-edit"></i> Edit</button></a>
   <a href="{{ path('rec_deleteUser', {'id': rec.id}) }}"> <button type="button" class="btn btn-light btn-round px-2">
   
   <i class="fas fa-trash"></i>
                                   delete</button></a>

    {% endif %}
                </div> <div class="clearfix"></div>
    </div>
</div>

<style>
    .table-row:hover {
        background-color: #f8f9fa;
    }
    .table-row:hover td {
        color: #007bff;
    }
    .table-row:hover .btn {
        background-color: #f8f9fa;
        color: #007bff;
    }
</style>


{% endblock %}

{% endblock %}{% endblock %}
{% block js %}
<script>
    function expandImage(image) {
        // Vérifiez si l'image est déjà agrandie
        if (image.classList.contains('expanded-image')) {
            // Si oui, réduisez-la
            image.classList.remove('expanded-image');
        } else {
            // Sinon, agrandissez-la
            image.classList.add('expanded-image');
        }
    }
</script>
{% endblock %}

templates/reclamation/show.html.twig
{% extends 'back_base.html.twig' %}

{% block content %}
<style>

.small-image {
    max-width: 100px;
    max-height: 100px;
    transition: all 0.3s ease; /* Animation de transition pour un agrandissement en douceur */
}

.expanded-image {
    max-width: none; /* Supprimez la limitation de la largeur */
    max-height: none; /* Supprimez la limitation de la hauteur */
    cursor: zoom-out; /* Changez le curseur pour indiquer qu'il est possible de cliquer à nouveau pour réduire l'image */
}
    .custom-margin-top {
        margin-top: 7rem; 
    }
    .center {
        text-align: center;
    }
    .label-value {
        margin-left:20px;
        text-decoration: underline;
        display: inline-block; 
        width:200px; 
    }
    .btn-row {
        margin-top: 10px;
    }
    .btn:hover {
        background-color: #f8f9fa;
        color: #007bff;
    }
</style>

<div class="content-wrapper" style="margin-left:200px;margin-right:200px;margin-top:-100px;">
    <div class="container-fluid">
        <div class="card-content">
            <div class="row justify-content-center mt-5 mb-5">
                <div class="col-12 col-lg-22">
                    <div class="card"><br>
                        <h3 class="center">Claim Details</h3>
                        <br> <div class="table-responsive">
                    

<table class="table">
        <tbody>
          
         <tr>
        <th style="color: white;">map</th>
          <td style="width:250px; height: 250px;">
    <iframe src='https://www.google.com/maps?q={{ reclamation.latitude }},{{ reclamation.longitude }}&h1=es;z=14&output=embed' style="width: 100%; height: 100%; border: 0;"></iframe>
</td>
 </tr>
         <tr>
        <th style="color: white;">image</th>
          <td>
       {% if reclamation.getFileName() is not null %}  
<img src="{{ asset('uploads/' ~ reclamation.fileName | split('/') | last) }}" alt="{{ reclamation.fileName }}" class="small-image" onclick="expandImage(this)">
    {% else %} ------{% endif %}</p>

    </td>
        </tr>
    </td>
        </tr>
            <tr>
                <th style="color: white;">Id</th>
                <td style="color: white;">{{ reclamation.id }}</td>
            </tr>
            <tr>
                 <th style="color: white;">Label</th>
                <td style="color: white;">{{ reclamation.libelle }}</td>
            </tr>
            <tr>
    <th style="color: white;">Date Claim</th>
    <td style="color: white;">{{ reclamation.dateDecl ? reclamation.dateDecl|date('Y-m-d H:i:s') : ''}}</td>
</tr>
<tr>
    <th style="color: white;">Date Sinistre</th>
    <td style="color: white;">{{reclamation.dateSin ? reclamation.dateSin|date('Y-m-d H:i:s') : ''  }}</td>
</tr>

              <tr>
    <th style="color: white;">Content</th>
    <td style="color: white;">
        <p>{{ reclamation.contenuRec }}</p>
    </td>
</tr>
            <tr>
                 <th style="color: whie;">Reponse</th>
                <td style="color: white;">{{ reclamation.reponse }}</td>
            </tr>
              <tr>
                 <th style="color: whie;">Compensation Id</th>
                <td style="color: white;">
            
                       {% if reclamation.getIndemnissation() is not null %}
                                {{ reclamation.getIndemnissation().getId() }}
                            {% else %}
                                -----
                            {% endif %}
                </td>
            </tr>
                       
                   
              </tbody></table>
                <div class="col-12 col-lg-7">
                    <br>
                    
                        <a href="{{ path('reclamationAdmin_edit',{'id':reclamation.id}) }}">
                            <button type="button" class="btn btn-light btn-round px-4"><i class="icon-lock"></i>Edit</button>
                        </a>
              
                    
                        <a href="{{ path('rec_delete', {'id': reclamation.id}) }}">
                            <button type="button" class="btn btn-light btn-round px-4"><i class="fas fa-trash"></i>Delete</button>
                        </a>
                   
                    
                        {% if reclamation.getIndemnissation() is not null %}
                            <a href="{{ path('indemnisation_show', {'id': reclamation.getIndemnissation().getId()}) }}" class="btn btn-light btn-round px-4"></i>
                                View Compensation</button>
                            </a>
                        {% endif %}
                    
                        <a href="{{ path('app_reclamation_admin') }}" class="btn btn-light btn-round px-4"> Cancel</a>
                    
                   
                </div>
                <br>
                <br>
            </div>
            
        </div>
        
    </div>
    
</div>
{% endblock %}
{% block js %}
<script>
    function expandImage(image) {
        if (image.classList.contains('expanded-image')) {
            image.classList.remove('expanded-image');
        } else {
            image.classList.add('expanded-image');
        }
    }
</script>
{% endblock %}