src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $montant = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_effet = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_exp = null;

    #[ORM\Column(length: 255)]
 
    private ?array $full_doa = null;

    #[ORM\ManyToOne(targetEntity: Assurance::class)]
    //#[ORM\JoinColumn(nullable: false,onDelete:'CASCADE')]
    private ?Assurance $doaCom = null;


    #[ORM\ManyToOne(inversedBy: 'commandes')]
    //#[ORM\JoinColumn(nullable: false,onDelete:'CASCADE')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    //#[ORM\JoinColumn(nullable: false,onDelete:'CASCADE')]
    private ?Offre $off = null;

    #[ORM\Column]
    #[Assert\Positive(message:"The Value Must Be Positive!")]
    private ?float $InsValue = null;

    #[ORM\Column(type: 'boolean')]
    private $isChecked = false;

    public function getIsChecked(): bool
    {
        return $this->isChecked;
    }

    public function setIsChecked(bool $isChecked): static
    {
        $this->isChecked = $isChecked;

        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateEffet(): ?\DateTimeInterface
    {
        return $this->date_effet;
    }

    public function setDateEffet(\DateTimeInterface $date_effet): static
    {
        $this->date_effet = $date_effet;

        return $this;
    }

    public function getDateExp(): ?\DateTimeInterface
    {
        return $this->date_exp;
    }

    public function setDateExp(\DateTimeInterface $date_exp): static
    {
        $this->date_exp = $date_exp;

        return $this;
    }

    public function getFullDoa(): ?array
    {
        return $this->full_doa;
    }

    public function setFullDoa(array $full_doa): static
    {
        $this->full_doa = $full_doa;

        return $this;
    }

    public function getDoaCom(): ?assurance
    {
        return $this->doaCom;
    }

    public function setDoaCom(?assurance $doaCom): static
    {
        $this->doaCom = $doaCom;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getInsValue(): ?float
    {
        return $this->InsValue;
    }

    public function setInsValue(float $InsValue): static
    {
        $this->InsValue = $InsValue;

        return $this;
    }

    public function getOff(): ?Offre
    {
        return $this->off;
    }

    public function setOff(?Offre $off): static
    {
        $this->off = $off;

        return $this;
    }

}

src/Entity/Police.php
<?php

namespace App\Entity;

use App\Repository\PoliceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: PoliceRepository::class)]
#[UniqueEntity(fields: ['police_name'], message: 'An identical police name already exists.')]
class Police
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "The police name is required.")]
    #[Assert\Length(
        max: 30,
        maxMessage: "The police name cannot exceed {{ limit }} characters."
    )]
    #[Assert\Regex(
        pattern: '/^[A-Z][a-zA-Z\s]*$/',
        message: "The police name must start with an uppercase letter and contain only letters."
    )]
    private ?string $police_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "The police description is required.")]
    #[Assert\Regex(
        pattern: '/^[A-Z].*$/',
        message: "The description must start with an uppercase letter."
    )]
    #[Assert\Regex(
        pattern: '/\.$/',
        message: "The description must end with a period."
    )]

    private ?string $Description_police = null;

    #[ORM\ManyToOne(inversedBy: 'police')]
    #[Assert\NotNull(message: "A claim must be selected.")] 
    //#[ORM\JoinColumn(nullable: false,onDelete:'CASCADE')]
    private ?Sinistre $sinistre = null;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPoliceName(): ?string
    {
        return $this->police_name;
    }

    public function setPoliceName(?string $police_name): self
    {
        $this->police_name = $police_name;

        return $this;
    }

    public function getDescriptionPolice(): ?string
    {
        return $this->Description_police;
    }

    public function setDescriptionPolice(?string $Description_police): self
    {
        
        $this->Description_police = preg_replace('/\s+/', ' ', trim($Description_police));

        return $this;
    }

    public function getSinistre(): ?Sinistre
    {
        return $this->sinistre;
    }

    public function setSinistre(?Sinistre $sinistre): self
    {
        $this->sinistre = $sinistre;

        return $this;
    }
}

src/Entity/Sinistre.php
<?php

namespace App\Entity;

use App\Repository\SinistreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: SinistreRepository::class)]
#[UniqueEntity(fields: ['sin_name'], message: 'An identical claim name already exists.')]
class Sinistre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "The claim name is required.")]
    #[Assert\Length(
        max: 30,
        maxMessage: "The claim name cannot exceed {{ limit }} characters."
    )]
    #[Assert\Regex(
        pattern: '/^[A-Z][a-zA-Z\s]*$/',
        message: "The claim name must start with an uppercase letter and contain only letters."
    )]

    private ?string $sin_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "The claim description is required.")]
    #[Assert\Regex(
        pattern: '/^[A-Z].*$/',
        message: "The description must start with an uppercase letter."
    )]
    #[Assert\Regex(
        pattern: '/\.$/',
        message: "The description must end with a period."
    )]

    private ?string $description_sin = null;


    #[ORM\OneToMany(targetEntity: Police::class, mappedBy: 'sinistre')]
    private Collection $police;

    #[ORM\Column(length: 255)]
    

    
    private ?string $imagePath = null;

    public function __construct()
    {
        $this->police = new ArrayCollection();
    }
     

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSinName(): ?string
    {
        return $this->sin_name;
    }

    public function setSinName(?string $sin_name): static
    {
        $this->sin_name = $sin_name;

        return $this;
    }

    public function getDescriptionSin(): ?string
    {
        return $this->description_sin;
    }

    public function setDescriptionSin(?string $description_sin): static
    {
        $this->description_sin = $description_sin = preg_replace('/\s+/', ' ', trim($description_sin));

        return $this;
    }

    /**
     * @return Collection<int, Police>
     */
    public function getPolice(): Collection
    {
        return $this->police;
    }

    public function addPolice(Police $police): static
    {
        if (!$this->police->contains($police)) {
            $this->police->add($police);
            $police->setSinistre($this);
        }

        return $this;
    }

    public function removePolice(Police $police): static
    {
        if ($this->police->removeElement($police)) {
            // set the owning side to null (unless already changed)
            if ($police->getSinistre() === $this) {
                $police->setSinistre(null);
            }
        }

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(?string $imagePath): static
    {
        $this->imagePath = $imagePath;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'First name cannot be blank')]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Last name cannot be blank')]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Email cannot be blank')]
    #[Assert\Email(message: 'Invalid email format')]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Password cannot be blank')]
    #[Assert\Length(min: 8, minMessage: 'Password must be at least 8 characters long')]
    #[Assert\Regex(
        pattern: '/^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&]).{8,}$/',
        message: 'Password must contain at least one uppercase letter, one digit, and one special character'
    )]
    private ?string $password = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Phone number cannot be blank")]
    private ?int $phone_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message:"Please enter your birth date.")]
    #[Assert\LessThanOrEqual("today", message:"Birth date must not be in the future.")]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\Column(type: 'json')]
    #[Assert\NotBlank(message:"No roles selected.")]
    private ?array $roles = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: 'boolean')]
    private $isBlocked = false;
    
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $secret = null;

    #[ORM\Column(type: 'string', length: 255)]
    private $googleId;

    #[ORM\Column(type: 'text', nullable: true)]
    private $avatar;

    #[ORM\Column(type: 'string', length: 255)]
    private $hostedDomain;

    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'Avis')]
    private Collection $client;
    #[ORM\OneToMany(targetEntity: Commande::class, mappedBy: 'user')]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->client = new ArrayCollection();
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): void
    {
        $this->googleId = $googleId;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): void
    {
        $this->avatar = $avatar;
    }

    public function getHostedDomain(): ?string
    {
        return $this->hostedDomain;
    }

    public function setHostedDomain(?string $hostedDomain): void
    {
        $this->hostedDomain = $hostedDomain;
    }
    
    public function getSecret(): ?string
    {
        return $this->secret;
    }

    public function setSecret(?string $secret): static
    {
        $this->secret = $secret;

        return $this;
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?int $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getRoles()
    {
        return $this->roles;
    }

    public function setRoles(?array $roles): static
{
    $this->roles = $roles;
    return $this;
}

    public function getSalt(){return null;}

    public function eraseCredentials(){}
    public function getUsername(): string{return $this->first_name." ".$this->last_name;}

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    public function isBlocked(): bool
    {
        return $this->isBlocked;
    }

    public function setIsBlocked(bool $isBlocked): static
    {
        $this->isBlocked = $isBlocked;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getClient(): Collection
    {
        return $this->client;
    }

    public function addClient(Avis $client): static
    {
        if (!$this->client->contains($client)) {
            $this->client->add($client);
            $client->setAvis($this);
        }

        return $this;
    }

    public function removeClient(Avis $client): static
    {
        if ($this->client->removeElement($client)) {
            // set the owning side to null (unless already changed)
            if ($client->getAvis() === $this) {
                $client->setAvis(null);
            }
        }

        return $this;
    }
}

templates/back/CommandeBack.html.twig
{% extends 'back_base.html.twig' %}

{% block content %}
    <div class="clearfix"></div>
    <div class="content-wrapper" style="margin-left:0px;">
        <div class="container-fluid">
            <div class="row justify-content-center mb-4">
                <div class="col-12 ">
                    <!-- Orders Table -->
                    <div class="card">
                        <div class="card-header">Orders Table</div>
                        <div class="table-responsive text-center">
                            <table class="table align-items-center table-flush table-borderless table-sm">
                                <!-- Table Header -->
                                <thead>
                                    <tr>
                                        <th>Order ID</th>
                                        <th>Full Premium</th>
                                        <th>Effective Date</th>
                                        <th>Expiration Date</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <!-- Table Body -->
                                <tbody>
                                    {% for cmd in command %}
                                        <tr>
                                            <td>{{ cmd.id }}</td>
                                            <td>{{ cmd.montant }}</td>
                                            <td>{{ cmd.dateEffet ? cmd.dateEffet|date('Y-m-d') : 'N/A' }}</td>
                                            <td>{{ cmd.dateExp ? cmd.dateExp|date('Y-m-d') : 'N/A' }}</td>
                                            <td>
                                               <a href="{{ path('delete_com', {'id': cmd.id}) }}" class="btn btn-light btn-round px-5">Delete</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="5">No Records Found</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- Chart Section -->
                    <div id="chart_div"></div>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" id="totalCommands" value="{{ totalCommands }}" />
{% for item in assurancesCommandsCounts %}
    <input type="hidden" id="assurance{{ loop.index }}" value="{{ item.commandCount }}" data-assurance-name="{{ item.assurance.nameins }}" />
{% endfor %}

<!-- Include Google Charts Library -->
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Assurances');
        data.addColumn('number', 'Count');

        // Dynamically populate data from hidden inputs
        {% for item in assurancesCommandsCounts %}
            var assuranceName{{ loop.index }} = document.getElementById('assurance{{ loop.index }}').getAttribute('data-assurance-name');
            var assuranceCount{{ loop.index }} = parseInt(document.getElementById('assurance{{ loop.index }}').value);
            data.addRow([assuranceName{{ loop.index }}, assuranceCount{{ loop.index }}]);
        {% endfor %}

        var options = {
    title: 'Insurances Bought',
    is3D: true,
    backgroundColor: 'transparent',
    width: 800,  // Set the width of the chart
    height: 600, // Set the height of the chart
    // Add any other customizations as needed
};

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>


{% endblock %}

templates/back/home.html.twig
{% extends 'back_base.html.twig' %}

templates/back/user.html.twig
{% extends 'back_base.html.twig' %}
{% block title %}{{ 'back.admin.title'|trans }}{% endblock %}
{% block content %}

<div class="row">
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <div class="card-title">Add User</div>
            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
            <div class="row mb-3">
                <div class="col-md-3">
                    <div class="form-group">
                        {{ form_row(form.first_name, {'attr': {'class': 'form-control', 'placeholder': 'Enter Your Name'}}) }}

                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        {{ form_row(form.last_name, {'attr': {'class': 'form-control', 'placeholder': 'Last Name'}}) }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        {{ form_row(form.email, {'attr': {'class': 'form-control', 'placeholder': 'Enter Your Email Address'}}) }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        {{ form_row(form.phone_number, {'attr': {'class': 'form-control', 'placeholder': 'Enter Your Mobile Number'}}) }}
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-3">
                    <div class="form-group">
                        {{ form_row(form.password, {'attr': {'class': 'form-control', 'placeholder': 'Enter Password'}}) }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                    {{ form_row(form.birth_date, {'attr': {'class': 'form-control', 'placeholder': 'Enter Birth Date', 'type': 'date'}}) }}
                    </div>
                </div>
                <div class="col-md-3">
                <div class="form-group">
                    {{ form_row(form.roles, {'attr': {'class': 'form-control role-selector', 'placeholder': 'Enter Roles'}, 'multiple': 'multiple'}) }}
                </div>
            </div>
                <div class="col-md-3">
                    <div class="form-group mt-4">
                        <button type="submit" class="btn btn-light" style=" color: yellow; padding: 15px; width: 150px;" ><i class="icon-lock"></i> Submit</button>
                    </div>
                </div>
            </div>

            {{ form_end(form) }}
        </div>
    </div>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <div class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" id="search" class="form-control" placeholder="Search here">
                </div>
            </div>
            <br>
            <span class="search-result-label">Search result:</span><span class="fa arrow"></span>
            <table class="table table-hover">
            <tr class="text-center">
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Blocked</th>
                    </tr>
                <tbody id="entitiesNav">
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
<br><br><br>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script type="text/javascript">
    jQuery(document).ready(function() {
        var searchRequest = null;
        $("#search").keyup(function() {
            var minlength = 1;
            var that = this;
            var value = $(this).val();
            var entitySelector = $("#entitiesNav").html('');
            if (value.length >= minlength ) {
                if (searchRequest != null)
                    searchRequest.abort();
                searchRequest = $.ajax({
                    type: "GET",
                    url: "{{ path('ajax_search') }}",
                    data: {
                        'q' : value
                    },
                    dataType: "text",
                    success: function(msg){
                        //we need to check if the value is the same
                        if (value===$(that).val()) {
                            var result = JSON.parse(msg);
                            $.each(result, function(key, arr) {
                                $.each(arr, function(id, value) {
                                    if (key === 'users') {
                                        if (id !== 'error') {
                                            console.log(value[0]);
                                            var blockButtonLabel = value[3] ? 'Unblock' : 'Block';
                                            var blockButtonClass = value[3] ? 'btn btn-danger' : 'btn btn-warning';
                                            var blockButtonPath = value[3] ? "{{ path('unblock_user', {'id': 'dummy'}) }}" : "{{ path('block_user', {'id': 'dummy'}) }}";
                                            blockButtonPath = blockButtonPath.replace('dummy', id);
                                            entitySelector.append('<tr class="text-center"><td>'+value[0]+'</td><td>'+value[1]+'</td><td><b>'+value[2]+'</td><td><a href="'+blockButtonPath+'" class="'+blockButtonClass+'">'+blockButtonLabel+'</a></td></tr>');
                                        } else {
                                            entitySelector.append('<li class="errorLi">'+value+'</li>');
                                        }
                                    }
                                });
                            });
                        }
                    }
                });
            }
        });
    });
</script>

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">User Table</h5>
            <div class="table-responsive">
            <div class="count" style="font-size :15px;">
                <a>Number of users: {{ pagination.getTotalItemCount }}</a>
            </div>

            <table class="table table-hover">
                <thead>
                    <tr class="text-center">
                        <th{% if pagination.isSorted('u.id') %} class="sorted"{% endif %}>
                            {{ knp_pagination_sortable(pagination, 'Id', 'u.id') }}
                        </th>
                        <th{% if pagination.isSorted('u.firstName') %} class="sorted"{% endif %}>
                            {{ knp_pagination_sortable(pagination, 'First', 'u.firstName') }}
                        </th>
                        <th>{{ knp_pagination_sortable(pagination, 'Last', 'u.lastName') }}</th>
                        <th>{{ knp_pagination_sortable(pagination, 'Email', 'u.email') }}</th>
                        <th>{{ knp_pagination_sortable(pagination, 'Phone', 'u.phoneNumber') }}</th>
                        <th>{{ knp_pagination_sortable(pagination, 'BDate', 'u.birthDate') }}</th>
                        <th>{{ knp_pagination_sortable(pagination, 'Role', 'u.roles') }}</th>
                        <th>{{ knp_pagination_sortable(pagination, 'Verified', 'u.verified') }}</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in pagination %}
                        <tr class="text-center">
                            <td>{{ user.id }}</td>
                            <td>{{ user.getFirstName() }}</td>
                            <td>{{ user.getLastName() }}</td>
                            <td>{{ user.getEmail() }}</td>
                            <td>{{ user.getPhoneNumber() }}</td>
                            <td>{{ user.birthDate | date('Y-m-d') }}</td>
                            <td>
                                {% for role in user.getRoles() %}
                                    {{ role }}
                                    {% if not loop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                            <td>{{ user.IsVerified() ? 'Yes' : 'No' }}</td>
                            <td>
                                <div class="btn-group">
                                    <form action="{{ path('app_admin_user_delete', {'id': user.id}) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this user?')">
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                    <a href="{{ path('app_admin_user_edit', {'id': user.id}) }}" class="btn btn-warning">Update</a>
                                </div>
                            </td>   
                        </tr>
                    {% endfor %}    
                </tbody>
            </table>
            </div>
            <div class="navigation" style="margin-left:350px;">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}